name: ${name}
main: ${plugin.mainClass}
version: ${project.version}
author: rmsy

permissions:
  displaynames.edit:
    description: Allows editing of all display names.
    default: op
    children:
      displaynames.edit.own: true
      displaynames.edit.others: true
  displayname.edit.own:
    description: Allows editing of the user's display name.
    default: op
  displayname.edit.own:
    description: Allows editing of other users' display names.
    default: op
